### ISSUE TITLE
Object-oriented programming does not need classes.

### ISSUE THREAD

**Issue by mk-pmb** [m50d/m50d.github.com#1]
Hi! I've been reading a lot of your blog, some of it was very interesting, thanks!

In `2014-12-08-object-oriented-essentialism.md`, you seem to confuse the class- or taxonomy-oriented programming with object-oriented programming. This confusion is very popular. So popular even, that ECMAScript nowadays uses a keyword `class` to make it easier for newcomers to stick to their concepts, and don't need to understand that behind that curtain, it's all about objects. First-class objects, not restricted to some class, but as a concept of their own. (They can optionally be based on prototypes, usually at measurable performance cost.) If you're interested in more details, [Douglas Crockford explains them here](https://www.youtube.com/watch?v=RO1Wnu-xKoY), starting at 24m08s. (*)
I hope this helps your thoughts about language choice and design!

From your blog it seems you don't usually deal with JavaScript. In case its objects get you interested, I recommend to watch [all of CoJS](https://www.youtube.com/playlist?list=PL7664379246A246CB), in order to learn upfront about a lot of its shortcomings common pitfalls.

(*) Technicalities about how objects work in ES start at 16m00s. The origins of ES's class-free objects are explained in Volume 1 of CoJS, starting at 1h16m10s (Simula, Smalltalk) and 1h21m38s (Self).

PS: Closing because no fix required.

**Comment by m50d** [comment]
Hi,

Glad to hear you read it, and sorry I haven't written much of late. FWIW this sort of discussion might be more visible on the disqus comments rather than GitHub issues.
I can't/won't watch videos, so I can't comment on the contents of your links. I will say that "object-oriented" means different things to different people, and I take a descriptivist view of what words mean; I'd prefer to use the consensus meaning that will be understood by most readers, even if that's drifted away from the original coinage. I'm aware that the JavaScript community has a different definition of many related terms from that used in the wider programming community, but my audience is more the latter than the former.

**Comment by mk-pmb** [comment]
> I can't/won't watch videos,

No problem, it's just a mirror of how I won't use disqus. :-) We all have to pick which cloud services we accept.
Majority is a strong argument for vocabulary, so maybe "class-free OOP" could be a way out. If you're not especially interested in JS, then the video parts boil down to:
- Some languages implement OOP by allowing to store functions on an object directly, instead of indirect lookup via some class.
- You can still achieve the indirect lookup by means of delegation: Have each object store a list of its parents (JS: max. 1 parent). If a method is called on an object that doesn't implement it, climb up its ancestor tree (JS: "prototype chain") to maybe find the function there. If found, run it on the original object.
- Class-free OOP can easily simulate classes. Crockford claims that the reverse relation is false (probably unless you accept writing a full interpreter) and that this makes class-free OOP a stronger computational model than class-based OOP is.

In another lecture he expressed hope that mankind will soon invent a better class-free OOP language than JS, and I agree with that. So if you ever find one, make sure to let me (and other readers) know. :-)

**Comment by m50d** [comment]
> Class-free OOP can easily simulate classes. Crockford claims that the reverse relation is false (probably unless you accept writing a full interpreter) and that this makes class-free OOP a stronger computational model than class-based OOP is.

It allows you to express things that you can't express in traditional OO, sure. The question is whether there's a good reason for not wanting to express those. IMO the (traditional) JS approach combines the worst aspects of the approaches I was trying to contrast in my post: it's ad-hoc and undiscoverable like FP, but still coupled like traditional OO.

**Comment by mk-pmb** [comment]
> The question is whether there's a good reason for not wanting to express those.

Oh right, I forgot an important aspect. The one about timing. To choose _when_ you want to express group membership.
One of DC's main arguments against class-based OOP is that it leads people to invent categories at an early stage in a project, when they least know what taxonomy could fit the thing they're going to build, and this tends to constrict API design ideas. That is probably more about how strict your language's type system is, as your article shows with the mammal vs. bird essentialism problem. In JS you can express either claim ("bats are mammals" or "bats are birds"), even machine-readable, but you're never forced to, especially not in an early stage when you're still figuring things out.

> it's ad-hoc and undiscoverable like FP

I have a vague idea what you mean with ad-hoc, but cannot find claims about discoverability in your article. Maybe I'm lacking some knowledge about FP that could explain what's "undiscoverable" about it.

> coupled like traditional OO.

I fail to guess what you could mean with "coupled". In the bat example, I could just store the bird's fly method on a mammal bat object, invoke it and it will work to the extent they're compatible. Flapping its wings might work, trying to steer its tail feathers will probably throw an exception unless you equip some first.

``` javascript
dracu = new Bat();
(dracu instanceof Mammal)   // -> true
(dracu instanceof Bird)     // -> false
dracu.fly = (new Bird()).fly;
dracu.fly(destLocation);
```

Modifying the bat is optional. I could instead just make a new temporary object that delegates everything to the bat that shall fly, except for the fly method, which I take from the bird.

``` javascript
temp = Object.create(dracu);
temp.fly = (new Bird()).fly;
temp.fly(destLocation);
```

Or I could actually skip all that "make a bat that can fly" boilerplate. A bat doesn't strictly need to learn how to fly if a bird knows how to do it. (Think possessed by a bird's ghost.)

``` javascript
someBirdGhost.fly.call(dracu);
```

With your taco example I'm not sure how you meant to throw a `MethodNotSupported` exception. Would you have to override the sandwich's `getTopSlice` method with one that throws the exception? I'd consider it confusing if your taco had that fake method, because my reflection API would tell me it has a method with that name, and then it's a surprise that I can't use it. In JS, you'd just erase that method, so that feature detection can determine that tacos can't `getTopSlice()`.

Since erasing a method in dead source is boring, let's assume an interactive multi-user food simulation program and fix a broken (pseudo-¹)class definition in vivo with live debugging. (Not recommended in production.)

``` javascript
// Part of server init
inherits(Taco, Sandwich);

// Some user requests a taco, so we create one:
tac = new Taco();
(tac.getTopSlice instanceof Function)   // -> true, user reports bug

// Connect as maintenance programmer and hotfix it:
tacoPt = Taco.prototype;
tacoPt.getTopSlice = null;    // Report to user: Fixed, try again.

// User checks their taco. The very same taco object (instance)
// that was created (instantiated) before the fix.
(tac.getTopSlice instanceof Function)   // -> false, but try anyway:
tac.getTopSlice();  // -> TypeError: tac.getTopSlice is not a function
```

The maintenance programmer is happy that the fix works as intended and edits the server init section of the source code to add the fix, so any newly-started server instances won't have the bug.

¹ "Pseudo-" because there is no class in JS, just the constructor and its prototype. Python might be able to modify real class definitions at runtime.

**Comment by m50d** [comment]
If it's not expressed (and perhaps not expressible?) in a statically safe way then I'm not interested, myself. I don't think it's worth us going through static types vs runtime checks; suffice it to say I know where I stand.

> I have a vague idea what you mean with ad-hoc, but cannot find claims about discoverability in your article. Maybe I'm lacking some knowledge about FP that could explain what's "undiscoverable" about it.

I think a big downside for FP (or specifically for the Haskell style of polymorphism) is that it's harder to know what a given term is / what you can do with it. If your `Bat extents Bird` then you know very directly that you can call `Bird` methods on it; if you model that as a typeclass then it's much harder to get from `Bat` to `fly()`. I think this does feed back to the essentialism idea: even in the real world where it isn't true, essentialist thinking is attractive because it's _easier_ to work with than the complexity of non-essentialist models of the world. Just as predictions of the death of hierarchical filesystems in favour of tagging have mostly not come to pass (even in GMail I end up using labels exclusively as folders).
